### ISSUE TITLE
Adding sorting to dtOptions causes the table data to be reloaded

### ISSUE THREAD

**Issue by MatiasKiuru** [l-lin/angular-datatables#101]
Hello!

This is what I'm trying to do: 
http://www.datatables.net/examples/basic_init/table_sorting.html 

But there appears to be some kind of bug that refreshes the table after sorting columns when using "order" in dtOptions.

Steps to reproduce:
1) Take your row click event example (or any other example should work) and add this line to it in order to add default ordering: 
<code>$scope.dtOptions.order = [[1, "desc"], [0,"asc"]];</code>
2) Then sort the table by clicking on one of the columns and after that click on one of the rows. 

You should observe that a request is sent to server to get the data and the table is reloaded.

**Comment by l-lin** [comment]
Solved with #146.

**Comment by fudali** [comment]
Hello! It looks like I still experience this issue in v0.5.7. The issue is exactly the same as described and I think it might not be related to #146
