### ISSUE TITLE
Can't bind to 'dtOptions' since it isn't a known property of 'table'. 

### ISSUE THREAD

**Issue by ishanambade** [l-lin/angular-datatables#1135]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- node version:8.9.1
- npm version:5.5.1
- angular version:
- jquery version:3.2.1
- datatables version:1.10.16
- angular-datatables version:4.4.1
- angular-cli version:1.5.0

## What's the problem?

Can we use this angular-datatables with 1.5.2 angular/cli  as im getting the error 
"Can't bind to 'dtOptions' since it isn't a known property of 'table'. "

**Comment by izzycole** [comment]
i have the same problem using angular 5.0.0, angular-cli: 1.5.0

**Comment by l-lin** [comment]
I released a version 5.0.0 of angular-datatables. Please check if that solves your issues.

**Comment by eduardotrzan** [comment]
Hi @l-lin,
I'm having the same issue. On same versions.
I'm trying the version you mentioned and seems that it's still broken.
Cheers

**Comment by FritzHerbers** [comment]
Might be a problem you haven't imported DataTablesModule in your module.
https://l-lin.github.io/angular-datatables/#/getting-started

**Comment by HabibRh26** [comment]
I think , I followed all steps mentioned above but still getting the error, below are the images:<br> error that I am receiving: 
![er](https://user-images.githubusercontent.com/47397271/145711798-1035a8e7-2913-4710-bf16-f7c944ebbef6.png)

 <br> `app.module.ts` file <br>
![app-mod](https://user-images.githubusercontent.com/47397271/145711629-7be72c42-b09a-42bf-ac04-d655db0e9d95.png) <br>  my `return-list` component `ts` file <br>
![compo-1](https://user-images.githubusercontent.com/47397271/145711661-d2c3dcc7-61ba-4677-98fd-659007cae02e.png) <br> 
![compo-2](https://user-images.githubusercontent.com/47397271/145711691-83a24830-bc02-46dd-988a-e447f1280299.png)
<br> and here is the `html` file <br> 
![html](https://user-images.githubusercontent.com/47397271/145711728-3b58c880-1996-48cc-90d6-62e265d9ed18.png)
<br>
Is there anything I am missing ?

**Comment by sathishbabu992** [comment]
anybody find any solutions for this problem

**Comment by mostafaosmanNodejs** [comment]
not build with --prod
