### ISSUE TITLE
datatables for angular4

### ISSUE THREAD

**Issue by zxdmrg** [l-lin/angular-datatables#998]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 4.0.0
- jquery version: 3.2.1
- datatables version: 1.10.13
- angular-datatables version: 2.2.0
- angular-MM version: 

## What's the problem?
Error encountered resolving symbol values statically.Calling function 'makeDecorator',

angular-datatables/node_modules/@angular/core/src/metadata/ng_module.d.ts

**Comment by illiniguy** [comment]
For now I pulled the .module.ts and directive.ts from the source on Github into my own module in my code and it works fine.

**Comment by yunClouds** [comment]
@illiniguy 
Can I trouble you for more details how to solve it? thanks alot

**Comment by illiniguy** [comment]
Just add a copy of the .directive.ts and .module.ts files to your project. Found here (for master):

[https://github.com/l-lin/angular-datatables/tree/master/src](url)

Then import that local module file instead of the angular-datatables one. Works for me until they upgrade to support v4.

**Comment by yunClouds** [comment]
@illiniguy 
First of all, Thanks alot illiniguy . I did as you said，but there has some problem  as shown in the figure:
![error](https://cloud.githubusercontent.com/assets/26613310/24796346/3743b7dc-1bbf-11e7-98d8-9aef5b009017.jpg)
How did you solve it?

**Comment by l-lin** [comment]
You need to add the typings of `jQuery` and `DataTables`:
```
npm install @types/jquery --save-dev
npm install @types/datatables.net --save-dev
```

**Comment by illiniguy** [comment]
Yep, apologies. I already had references to those libraries in my project, the latter before trying this library.

**Comment by l-lin** [comment]
I released the version [4.0.0](https://github.com/l-lin/angular-datatables/releases/tag/v4.0.0).
It should be ok now. Tell me if you still have trouble using with Angular 4.x.x.

**Comment by illiniguy** [comment]
Set it up just now. Seems to be working great. Thanks for the update!

**Comment by matthewhegarty** [comment]
I still get the error.
I have upgraded to angular-datatables 4.0.0 and I still get the [above error](https://github.com/l-lin/angular-datatables/issues/937).  I've tried deleting `node_modules`, `npm cache clean` and then `npm install`.

```
angular version: 4.0.0
datatables version: 4.0.0
ng version: 1.0.1
node version: 6.9.5
```

**Comment by l-lin** [comment]
I honestly don't know why it does not work... With `@angular/cli` version 1.0.0, it works as expected, and just with one path, it won't work...
So you can:
- either revert back to version 1.0.0 of angular-cli
- either declare the DataTableModule by using `forRoot()`:
```typescript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { DataTablesModule } from 'angular-datatables';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,

    DataTablesModule.forRoot()
  ],
  providers: [],
  bootstrap: [ AppComponent ]
})
export class AppModule {}
```

**Comment by matthewhegarty** [comment]
Thanks for the response. 

- Using `forRoot()` does fix the issue.
- Rolling back to `angular-cli@1.0.0` doesn't help - I get the same error

Otherwise, all I can do to fix is to roll back to the pre-4.0.0 version

My `ng version`:
```
$ ng version
@angular/cli: 1.0.1
node: 6.9.5
os: linux x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0
```

**Comment by l-lin** [comment]
Using angular-cli 1.0.0 and angular 4.0.3 seem to work for me. Check the [package.json of my demo](https://github.com/l-lin/angular-datatables/blob/master/demo/package.json).

**Comment by andikanugraha11** [comment]
I also experienced the same thing, after reading this issue my program can run by adding forRoot on the DataTableModule

**Comment by andikanugraha11** [comment]
I also experienced the same thing, after reading this issue my program can run by adding forRoot on the DataTablesModule

**Comment by LexBel-co** [comment]
i had the same issue, then i added DataTablesModule.forRoot() to my module, and  fixed the issue

**Comment by AshuSingh07** [comment]
Using  DataTablesModule.forRoot() fixed my issue.

Overloaded Thanks 👍

**Comment by ajsnyde** [comment]
Added forRoot() to line 18 of angular-datatables.module.js. Compiles now.
